### ISSUE TITLE
Zero-based day of week not working correctly.

### ISSUE THREAD

**Issue by KathyApplebaum** [RedHogs/cron-parser#23]
In both 2.6 and 2.7, using 0 for Sunday gives an error, but using 7 for Sunday gives the expected output. Possibly a regression error, since I see support for 7 was added in 2.4.

Exception in thread "AWT-EventQueue-0" org.joda.time.IllegalFieldValueException: Value 0 for dayOfWeek must be in the range [1,7]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:215)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:78)
	at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:466)
	at org.joda.time.DateTime.withDayOfWeek(DateTime.java:1748)
	at net.redhogs.cronparser.DateAndTimeUtils.getDayOfWeekName(DateAndTimeUtils.java:47)
	at net.redhogs.cronparser.builder.DayOfWeekDescriptionBuilder.getSingleItemDescription(DayOfWeekDescriptionBuilder.java:49)
	at net.redhogs.cronparser.builder.AbstractDescriptionBuilder.getSegmentDescription(AbstractDescriptionBuilder.java:52)
	at net.redhogs.cronparser.CronExpressionDescriptor.getDayOfWeekDescription(CronExpressionDescriptor.java:117)
	at net.redhogs.cronparser.CronExpressionDescriptor.getFullDescription(CronExpressionDescriptor.java:235)
	at net.redhogs.cronparser.CronExpressionDescriptor.getDescription(CronExpressionDescriptor.java:62)
	at net.redhogs.cronparser.CronExpressionDescriptor.getDescription(CronExpressionDescriptor.java:27)

**Comment by grahamar** [comment]
have you set the zero based option?
https://github.com/RedHogs/cron-parser/blob/master/cron-parser-core/src/main/java/net/redhogs/cronparser/Options.java#L64

**Comment by KathyApplebaum** [comment]
isZeroBasedDayOfWeek() returns true, but 0 does not parse.

**Comment by MCAllinder** [comment]
Hello. I am currently experiencing the same problem as Kathy. For example, "0,6" will be invalid while "6,7" gives Saturday and Sunday. 

isZeroBasedDayOfWeek() is true

Thanks!

**Comment by KathyApplebaum** [comment]
I have a suspect for where the problem is. In DayOfWeekDescriptionBuilder, lines 45-46, it looks like you're setting the day of the week to 7 if it's <= 1 and we're NOT zero based. The not in front of the zero based seems to be the issue -- if I step through and change that manually at break points, it behaves as expected.

**Comment by MCAllinder** [comment]
At quick glance, the issue appears to be with AbstractDescriptionBuilder line 19. If the expression is "0" then the description is set to ""

**Comment by grahamar** [comment]
I'll have a fix out for this today, thanks for the pull request @mcallinder
